Repository richardkriesman/wakeywakey, pull requests merged in 2019-05, with the labels that each got.

#46 Issue 64 Tapping a button multiple times opens multiple instances of a screen
  src/utils/screen/UIScreen.tsx
Labels: bug

#47 Issue 93 Destructive button has a shadow, but constructive button does not
  src/screens/settings/ScheduleAlarmsScreen.tsx
  src/screens/settings/SchedulesListScreen.tsx
Labels: bug

#40 Alarm logic
  assets/audio/MusicBox.mp3
  package.json
  src/screens/HomeScreen.tsx
  src/screens/__tests__/HomeScreen-test.tsx
  src/services/TimerService.ts
  src/utils/ObjectUtils.ts
  src/utils/Time.ts
  src/utils/screen/UIScreen.tsx
  yarn.lock
Labels: enhancement

#48 Issue 92 About screen
  assets/images/team-logo.png
  src/navigation/MainStackNavigator.tsx
  src/screens/AboutScreen.tsx
  src/screens/__tests__/AboutScreen-test.tsx
  src/screens/__tests__/__snapshots__/AboutScreen-test.tsx.snap
  src/screens/settings/AppSettingsScreen.tsx
Labels: enhancement

#50 Issue 82 Create schedule option values
  assets/audio/Birds.mp3
  assets/audio/Computer.mp3
  assets/audio/NormalAlarm.mp3
  assets/audio/Pager.mp3
  assets/audio/Rooster.mp3
  src/components/SelectPicker.tsx
  src/screens/settings/OptionsListScreen.tsx
  src/screens/settings/__tests__/__snapshots__/ScheduleOptionsScreen-test.tsx.snap
Labels: feature

#51 Issue 90 Add swiping to passcode screen
  src/App.tsx
  src/__tests__/__snapshots__/App-test.tsx.snap
  src/components/PasscodeInput.tsx
  src/components/SlideUpIndicator.tsx
  src/components/Slider.tsx
  src/components/__tests__/SlideUpIndicator-test.tsx
  src/components/__tests__/__snapshots__/PasscodeInput-test.tsx.snap
  src/components/__tests__/__snapshots__/SlideUpIndicator-test.tsx.snap
  src/components/index.tsx
  src/navigation/__tests__/__snapshots__/AppNavigator-test.tsx.snap
  src/screens/HomeScreen.tsx
  src/screens/__tests__/HomeScreen-test.tsx
  src/screens/__tests__/__snapshots__/AboutScreen-test.tsx.snap
  src/screens/__tests__/__snapshots__/HomeScreen-test.tsx.snap
  src/screens/__tests__/__snapshots__/ScheduleListScreen-test.tsx.snap
  src/screens/settings/__tests__/__snapshots__/EditAlarmScreen-test.tsx.snap
  src/screens/settings/__tests__/__snapshots__/MainSettingsScreen-test.tsx.snap
  src/screens/settings/__tests__/__snapshots__/PasscodeChangeScreen-test.tsx.snap
  src/screens/settings/__tests__/__snapshots__/ScheduleAlarmsScreen-test.tsx.snap
  src/screens/settings/__tests__/__snapshots__/ScheduleOptionsScreen-test.tsx.snap
  src/utils/screen/UIScreen.tsx
Labels: enhancement

#53 Issue 97 Play user-configured alarm sound when alarm is fired
  assets/audio/LoudAlarm.mp3
  assets/audio/Special.mp3
  src/models/Schedule.ts
  src/screens/HomeScreen.tsx
  src/screens/settings/OptionsListScreen.tsx
  src/screens/settings/__tests__/__snapshots__/ScheduleOptionsScreen-test.tsx.snap
  src/services/ScheduleService.ts
  src/utils/Audio.ts
Labels: enhancement

#54 Remove the "Hello, world!" text from the home screen
  src/screens/HomeScreen.tsx
Labels: enhancement

#55 Issue 98: Snooze functionality
  src/__tests__/__snapshots__/App-test.tsx.snap
  src/navigation/__tests__/__snapshots__/AppNavigator-test.tsx.snap
  src/screens/HomeScreen.tsx
  src/screens/__tests__/__snapshots__/HomeScreen-test.tsx.snap
  src/services/TimerService.ts
  src/utils/AlarmEvent.ts
Labels: feature

#56 Issue 46 Home screen gradient
  src/__tests__/__snapshots__/App-test.tsx.snap
  src/components/Clock.tsx
  src/components/SkyBackground.tsx
  src/components/Slider.tsx
  src/components/__tests__/__snapshots__/Clock-test.tsx.snap
  src/components/index.tsx
  src/constants/Animation.ts
  src/navigation/__tests__/__snapshots__/AppNavigator-test.tsx.snap
  src/screens/HomeScreen.tsx
  src/screens/__tests__/__snapshots__/HomeScreen-test.tsx.snap
  src/services/AlarmService.ts
  src/services/ScheduleService.ts
  src/services/TimerService.ts
  src/services/__mocks__/AlarmService.ts
  src/utils/AlarmUtils.ts
  src/utils/AppDatabase.ts
  src/utils/screen/UIScreen.tsx
Labels: feature
